//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fhir.Testing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fhir.Testing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;feed xmlns=&quot;http://www.w3.org/2005/Atom&quot;&gt;
        ///  &lt;title type=&quot;text&quot;&gt;This is my first Bundle&lt;/title&gt;
        ///  &lt;id&gt;urn:uuid:9bd5a5f0-b996-4b7e-a3b0-2ceda2784597&lt;/id&gt;
        ///  &lt;updated&gt;2014-01-18T17:38:04.5718111-06:00&lt;/updated&gt;
        ///  &lt;category term=&quot;http://hl7.org/fhir/tag/document&quot; scheme=&quot;http://hl7.org/fhir/tag&quot; /&gt;
        ///  &lt;entry&gt;
        ///    &lt;title type=&quot;text&quot;&gt;Composition Resource&lt;/title&gt;
        ///    &lt;id&gt;urn:guid:64dfa724-130c-4c58-9b00-3111fd020d93&lt;/id&gt;
        ///    &lt;content type=&quot;text/xml&quot;&gt;
        ///      &lt;Composition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string conn5_21_cid_example {
            get {
                return ResourceManager.GetString("conn5_21_cid_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;feed xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://www.w3.org/2005/Atom&quot;&gt;
        ///  &lt;title&gt;A sample FHIR document&lt;/title&gt;
        ///  &lt;id&gt;urn:uuid:500bee81-d973-4afe-b592-d39fe71e38&lt;/id&gt;
        ///
        ///  &lt;updated&gt;2013-05-28T22:12:21Z&lt;/updated&gt;     &lt;!-- Time the bundle was built --&gt;
        ///  &lt;!-- Author is required by the Atom spec. FHIR doesn&apos;t use it--&gt;
        ///  &lt;author&gt;
        ///    &lt;name&gt;Doctor Dave&lt;/name&gt;
        ///  &lt;/author&gt;
        ///  &lt;!-- This tag specifies unambiguously that this is a FHIR document bundle --&gt;
        ///  &lt;category term=&quot;http://hl7. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string conn5_21_example {
            get {
                return ResourceManager.GetString("conn5_21_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] example_resources {
            get {
                object obj = ResourceManager.GetObject("example_resources", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;feed xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///    xsi:schemaLocation=&quot;http://www.w3.org/2005/Atom ../../Documents/FHIR/Schemas/DSTU1_1/fhir-atom.xsd&quot;
        ///    xmlns=&quot;http://www.w3.org/2005/Atom&quot;&gt;
        ///    &lt;title&gt;A sample FHIR diagnostic report message&lt;/title&gt;
        ///    &lt;id&gt;urn:uuid:612bee81-d973-4afe-b592-d39fe71e39&lt;/id&gt;
        ///    &lt;updated&gt;2014-09-08T11:34:00+02:00&lt;/updated&gt; 
        ///    &lt;author&gt;
        ///        &lt;name&gt;Doctor Faustus&lt;/name&gt;
        ///    &lt;/author&gt;
        ///    &lt;category  term=&quot;http://hl7.org/fhir/tag/message&quot; scheme=&quot;http:// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string message_false_SlicingRegularTestProfile {
            get {
                return ResourceManager.GetString("message_false_SlicingRegularTestProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;feed xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        /// xsi:schemaLocation=&quot;http://www.w3.org/2005/Atom ../../Documents/FHIR/Schemas/DSTU1_1/fhir-atom.xsd&quot;
        /// xmlns=&quot;http://www.w3.org/2005/Atom&quot;&gt;
        ///    &lt;title&gt;A sample FHIR diagnostic report message&lt;/title&gt;
        ///    &lt;id&gt;urn:uuid:612bee81-d973-4afe-b592-d39fe71e39&lt;/id&gt;
        ///    &lt;updated&gt;2014-09-08T11:34:00+02:00&lt;/updated&gt; 
        ///    &lt;author&gt;
        ///        &lt;name&gt;Doctor Faustus&lt;/name&gt;
        ///    &lt;/author&gt;
        ///    &lt;category  term=&quot;http://hl7.org/fhir/tag/message&quot; scheme=&quot;http://hl7.or [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string message_SlicingRegularTestProfile {
            get {
                return ResourceManager.GetString("message_SlicingRegularTestProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Patient xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;text&gt;
        ///    &lt;!-- &lt;status value=&quot;generated&quot;/&gt; --&gt;
        ///    &lt;!-- gives error: text.status cardinality should be 1, is zero --&gt;
        ///    
        ///    &lt;div xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///      Everywoman, Eve. SSN:
        ///      444222222
        ///    &lt;/div&gt;
        ///  &lt;/text&gt;
        ///  &lt;contact&gt;
        ///    &lt;name value=&quot;John&quot;/&gt;
        ///  &lt;/contact&gt;
        ///  &lt;identifier&gt;
        ///    &lt;system value=&quot;http://hl7.org/fhir/sid/us-ssn&quot;/&gt;
        ///    &lt;value value=&quot;444222222&quot;/&gt;
        ///  &lt;/identifier&gt;
        ///  &lt;name&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Patient_CardinalityMinus {
            get {
                return ResourceManager.GetString("Patient_CardinalityMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Patient xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;text&gt;
        ///    &lt;status value=&quot;generated&quot;/&gt;
        ///    &lt;div xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///      Everywoman, Eve. SSN:
        ///      444222222
        ///    &lt;/div&gt;
        ///  &lt;/text&gt;
        ///  &lt;contact&gt;
        ///    &lt;name value=&quot;John&quot;/&gt;
        ///  &lt;/contact&gt;
        ///  &lt;identifier&gt;
        ///    &lt;system value=&quot;http://hl7.org/fhir/sid/us-ssn&quot;/&gt;
        ///    &lt;value value=&quot;444222222&quot;/&gt;
        ///  &lt;/identifier&gt;
        ///  &lt;name&gt;
        ///    &lt;use value=&quot;official&quot;/&gt;
        ///    &lt;family value=&quot;Everywoman&quot;/&gt;
        ///    &lt;given value=&quot;Eve&quot;/&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Patient_CardinalityPlus {
            get {
                return ResourceManager.GetString("Patient_CardinalityPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Patient xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;text&gt;
        ///    &lt;status value=&quot;generated&quot;/&gt;     
        ///    &lt;div xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///      Everywoman, Eve. SSN:
        ///      444222222
        ///    &lt;/div&gt;
        ///  &lt;/text&gt;
        ///  &lt;contact&gt;
        ///      &lt;!-- constraint: either name, telecom, address or organisation should be present --&gt;
        ///  &lt;/contact&gt;
        ///  &lt;identifier&gt;
        ///    &lt;system value=&quot;http://hl7.org/fhir/sid/us-ssn&quot;/&gt;
        ///    &lt;value value=&quot;444222222&quot;/&gt;
        ///  &lt;/identifier&gt;
        ///  &lt;name&gt;
        ///    &lt;use value=&quot;offi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Patient_ConstraintError {
            get {
                return ResourceManager.GetString("Patient_ConstraintError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Patient xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;text&gt;
        ///    &lt;status value=&quot;generated&quot;/&gt;
        ///    &lt;div xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///      Everywoman, Eve. SSN: 444222222
        ///    &lt;/div&gt;
        ///  &lt;/text&gt; 
        ///  &lt;identifier&gt;
        ///    &lt;system value=&quot;http://hl7.org/fhir/sid/us-ssn&quot;/&gt;
        ///    &lt;value value=&quot;444222222&quot;/&gt;
        ///  &lt;/identifier&gt;
        ///  &lt;name&gt;
        ///    &lt;use value=&quot;unofficial&quot;/&gt; &lt;!-- this is a invalid value for use and should give an error --&gt;
        ///    &lt;family value=&quot;Everywoman&quot;/&gt;
        ///    &lt;given value=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Patient_ErrorUse {
            get {
                return ResourceManager.GetString("Patient_ErrorUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Patient xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;text&gt;
        ///    &lt;status value=&quot;generated&quot; /&gt;
        ///    &lt;div xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///      &lt;table&gt;
        ///        &lt;tbody&gt;
        ///          &lt;tr&gt;
        ///            &lt;td&gt;Name&lt;/td&gt;
        ///            &lt;td&gt;Peter James &lt;b&gt;Chalmers&lt;/b&gt; (&amp;quot;Jim&amp;quot;)&lt;/td&gt;
        ///          &lt;/tr&gt;
        ///          &lt;tr&gt;
        ///            &lt;td&gt;Address&lt;/td&gt;
        ///            &lt;td&gt;534 Erewhon, Pleasantville, Vic, 3999&lt;/td&gt;
        ///          &lt;/tr&gt;
        ///          &lt;tr&gt;
        ///            &lt;td&gt;Contacts&lt;/td&gt;
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string patient_example {
            get {
                return ResourceManager.GetString("patient_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Patient xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;text&gt;
        ///    &lt;status value=&quot;generated&quot;/&gt;
        ///    &lt;div xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///      Everywoman, Eve. SSN:
        ///      444222222
        ///    &lt;/div&gt;
        ///  &lt;/text&gt;
        ///  &lt;contact&gt;
        ///    &lt;name value=&quot;John&quot;/&gt;
        ///  &lt;/contact&gt;
        ///  &lt;identifier&gt;
        ///    &lt;system value=&quot;http://hl7.org/fhir/sid/us-ssn&quot;/&gt;
        ///    &lt;value value=&quot;444222222&quot;/&gt;
        ///  &lt;/identifier&gt;
        ///  &lt;name&gt;
        ///    &lt;use value=&quot;official&quot;/&gt;
        ///    &lt;family value=&quot;Everywoman&quot;/&gt;
        ///    &lt;given value=&quot;Eve&quot;/&gt;
        ///	  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Patient_InvalidElement {
            get {
                return ResourceManager.GetString("Patient_InvalidElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Patient xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;text&gt;
        ///    &lt;status value=&quot;generated&quot;/&gt;
        ///    &lt;div xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///      Everywoman, Eve. SSN: 444222222
        ///    &lt;/div&gt;
        ///  &lt;/text&gt; 
        ///  &lt;identifier&gt;
        ///    &lt;system value=&quot;http://hl7.org/fhir/sid/us-ssn&quot;/&gt;
        ///    &lt;value value=&quot;444222222&quot;/&gt;
        ///  &lt;/identifier&gt;
        ///  &lt;name&gt;
        ///    &lt;use value=&quot;official&quot;/&gt; 
        ///    &lt;family value=&quot;Everywoman&quot;/&gt;
        ///    &lt;given value=&quot;Eve&quot;/&gt;
        ///  &lt;/name&gt;
        ///  &lt;telecom&gt;
        ///    &lt;system value=&quot;phone&quot;/&gt;
        ///    &lt;v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Patient_Valid {
            get {
                return ResourceManager.GetString("Patient_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Profile xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///    &lt;text&gt;
        ///        &lt;status value=&quot;empty&quot;/&gt;
        ///        &lt;div xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;No narrative was supplied for this Profile&lt;/div&gt;
        ///    &lt;/text&gt;
        ///    &lt;identifier value=&quot;urn:hl7.org:lipid-profile:v1&quot;/&gt;
        ///    &lt;version value=&quot;1.0.0&quot;/&gt;
        ///    &lt;name value=&quot;Example Lipid Profile&quot;/&gt;
        ///    &lt;publisher value=&quot;HL7 International&quot;/&gt;
        ///    &lt;telecom&gt;
        ///        &lt;system value=&quot;email&quot;/&gt;
        ///        &lt;value value=&quot;e.kramer@furore.com&quot;/&gt;
        ///    &lt;/telecom&gt;
        ///    &lt;description
        ///        value= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SlicingRegularTestProfile_expanded {
            get {
                return ResourceManager.GetString("SlicingRegularTestProfile_expanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///&lt;feed xmlns=&quot;http://www.w3.org/2005/Atom&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;title&gt;XDS Submission - prepared by Health Intersections Test Script&lt;/title&gt;
        ///  &lt;id&gt;urn:uuid:02f06039-da24-4585-953b-0e9da4e79f41&lt;/id&gt;
        ///  &lt;updated&gt;2013-07-01T13:11:33Z&lt;/updated&gt;
        ///  &lt;author&gt;
        ///    &lt;name&gt;XDS --&amp;gt; FHIR Reference Bridge&lt;/name&gt;
        ///    &lt;uri&gt;http://www.healthintersections.com.au/xds2fhir.js&lt;/uri&gt;
        ///  &lt;/author&gt;
        ///  &lt;entry xmlns=&quot;http://www.w3.org/2005/Atom&quot;&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xds_example {
            get {
                return ResourceManager.GetString("xds_example", resourceCulture);
            }
        }
    }
}
